export const scenes = [
  {
    number: "01",
    template: "opening",
    title: "The Future I'm Building",
    subtitle: "Oral Surgery • Business • Creativity",
    metadata: ["CLE 10 Capstone", "Jovan Pahal", "Future Plan / Personal System"],
    line: "A personal blueprint for building a future that combines healthcare, ownership, creativity, and freedom.",
  },
  {
    number: "02",
    template: "text-reveal",
    title: "Who I Am",
    kicker: "Connected System",
    line: "I want a future where I don't have to give up one side of myself to build another.",
    items: [
      "Healthcare / Science",
      "Business / Money",
      "Music Production",
      "Technology / Systems",
      "Photography / Visual Creativity",
      "Long-Term Goals / Freedom",
    ],
  },
  {
    number: "03",
    template: "archive",
    title: "This Started Early",
    kicker: "Archive / Early File",
    typed: "This started earlier than this project.",
    lines: [
      "This started earlier than this project.",
      "Kindergarten: I wanted to be a dentist.",
      "The idea stayed the same. The vision got bigger.",
    ],
    fileTitle: "Kindergarten Career Video",
    metadata: [
      "Topic: Future career",
      "Status: Original clue",
      "Updated vision: Oral surgery + ownership",
    ],
  },
  {
    number: "04",
    template: "quote",
    title: "Big Question",
    kicker: "Core Question",
    quote: "How can I build a future that combines healthcare, business, creativity, and freedom?",
    items: ["Healthcare", "Business", "Creativity", "Freedom"],
  },
  {
    number: "05",
    template: "dramatic-image",
    title: "Oral and Maxillofacial Surgery",
    kicker: "Career Direction",
    lines: [
      "Oral and maxillofacial surgery is the career I can actually see myself building toward.",
      "It is serious, skilled, and still connects to business and ownership.",
    ],
    objectLabel: "Oral Surgery",
  },
  {
    number: "06",
    template: "system-object",
    title: "Why It Fits Me",
    kicker: "Fit System",
    center: "Oral Surgery",
    items: ["Skill", "Healthcare", "Business", "Lifestyle", "Freedom", "Helping People"],
    line: "It connects serious work with long-term options.",
  },
  {
    number: "07",
    template: "split",
    title: "Healthcare, But With Ownership",
    kicker: "Ownership Path",
    line: "I want a healthcare path where I can help people and still build something of my own.",
    items: ["Care", "Skill", "Team", "Systems", "Ownership", "Growth"],
  },
  {
    number: "08",
    template: "pathway",
    title: "The Pathway",
    kicker: "Roadmap",
    roadmap: "High School Science -> University Prerequisites -> Dental School -> Licensing -> Specialty Training -> Oral Surgery -> Practice / Ownership / Expansion.",
    stages: [
      "High School Science",
      "University Prerequisites",
      "Dental School",
      "Licensing",
      "Specialty Training",
      "Oral Surgery",
      "Practice / Ownership / Expansion",
    ],
    branches: [
      "General Dentistry",
      "Other Dental Specialties",
      "Business / Practice Ownership",
    ],
  },
  {
    number: "09",
    template: "file-stack",
    title: "Education and Training Options",
    kicker: "Training Files",
    items: ["UBC", "University of Toronto", "University of Manitoba / OMFS Pathway", "Strategic First Year"],
    note: "UBC is my preferred path, but the smartest path is the one that helps me build the strongest grades, experience, and momentum.",
  },
  {
    number: "10",
    template: "sequence",
    title: "The Business Side of Dentistry",
    kicker: "Growth Sequence",
    line: "I don't just like the career. I like the idea of building and scaling the business behind it.",
    items: ["Team", "Systems", "Equipment", "Reputation", "Patient Experience", "Growth"],
    final: "One practice -> stronger systems -> more rooms -> better team -> another location -> future expansion.",
  },
  {
    number: "11",
    template: "practice-system",
    title: "What a Practice Actually Looks Like",
    kicker: "Behind The Scenes",
    line: "From the outside, a dental practice can look simple. Behind the scenes, it is a whole system.",
    items: [
      "Front desk",
      "Scheduling",
      "Hygienists",
      "Assistants",
      "Patients",
      "Equipment",
      "X-rays",
      "Decisions",
      "Dentist moving between rooms",
    ],
  },
  {
    number: "12",
    template: "rotating",
    title: "Technology in Dentistry",
    kicker: "Digital Scan",
    lines: [
      "A physical scan can become a digital model.",
      "This made dentistry feel modern, technical, and connected to how I already think.",
    ],
    stlPaths: [
      "assets/dental/Visualization_DigitalModelUnsectioned_18-28.stl",
      "assets/dental/Visualization_DigitalModelUnsectioned_38-48.stl",
    ],
  },
  {
    number: "13",
    template: "network",
    title: "Practice Expansion",
    kicker: "Expansion Field",
    line: "A practice can grow into something bigger than one office.",
    items: ["Planning", "Investment", "Equipment", "Growth", "Opportunity"],
    final: "A career can become a platform for building other things.",
  },
  {
    number: "14",
    template: "sequence",
    title: "Business Is a Skill Too",
    kicker: "Skill Transfer",
    line: "Even when a side project does not become huge, the skills still stay with you.",
    items: ["Build", "Test", "Learn", "Wrap Up", "Apply Later"],
    final: "The project might end, but the skill does not.",
  },
  {
    number: "15",
    template: "marquee",
    title: "Music Production",
    kicker: "Motion Loop",
    line: "Producing is creative, but it is also technical.",
    items: ["Sound selection", "Arrangement", "Rhythm", "Mixing", "Collaboration", "Taste", "Practice"],
    final: "You need to be good at a lot of things to be a producer.",
  },
  {
    number: "16",
    template: "hover-image",
    title: "Waiting for the Right Moment",
    kicker: "Photography",
    quote: "You can always delete a bad picture, but you can't go back and take one you never tried to get.",
    final: "That applies to more than photography.",
    asset: "assets/generated/photo-placeholder.svg",
  },
  {
    number: "17",
    template: "command",
    title: "Opportunity Is a Resource",
    kicker: "Command Layer",
    lines: [
      "AI does not replace my thinking.",
      "It helps me move faster with ideas, research, organization, and building.",
      "I still make the decisions.",
    ],
    final: "Doing everything alone is not automatically better.",
    items: ["Ideas", "Research", "Organization", "Building", "Testing", "Decisions"],
  },
  {
    number: "18",
    template: "network",
    title: "Skill Opens Doors, People Show You Where They Are",
    kicker: "Network Quote",
    line: "Skill matters, but people matter too. Connections do not replace skill - they create opportunities for skill.",
    items: ["Dentistry / Oral Surgery", "Business", "Music", "Learning from people ahead"],
  },
  {
    number: "19",
    template: "skill-wheel",
    title: "Skills I'm Building",
    kicker: "Skill System",
    center: "The Future I'm Building",
    items: [
      "Business Thinking",
      "Creativity",
      "Technical Skill",
      "Long-Term Planning",
      "Adaptability",
      "Initiative",
    ],
  },
  {
    number: "20",
    template: "image-stack",
    title: "Making It Work Without Giving Things Up",
    kicker: "Connected Stack",
    line: "I do not want to give up one side of myself to build another.",
    items: ["Oral Surgery", "Business", "Music", "Tech", "Photography", "Lifeguarding / Work", "School"],
    final: "The goal is not to do everything randomly. It is to make everything support the future I'm building.",
  },
  {
    number: "21",
    template: "roadmap",
    title: "The Next Version of the Plan",
    kicker: "Final Build-Up",
    stages: ["Now", "Post-secondary", "Dental path", "Oral surgery", "Practice / business", "Keep creating"],
    items: [
      "Science / grades",
      "Meet or shadow oral surgeons",
      "Business / tech side projects",
      "Music sessions in university",
      "Photography / creative work",
      "Lifeguarding / work experience",
      "Earning money / responsibility",
      "Eventually building and scaling a practice",
    ],
  },
  {
    number: "22",
    template: "final",
    title: "Sources",
    kicker: "Final Reveal",
    items: [
      "Assignment",
      "Canadian Dental Association",
      "Canadian Association of Oral and Maxillofacial Surgeons",
      "UBC Dentistry",
      "University of Toronto Dentistry",
      "University of Manitoba Dentistry",
      "Personal experience",
    ],
    final: "Website built by Jovan Pahal.",
  },
];
