export const scenes = [
  {
    number: "01",
    template: "opening",
    title: "The Future I'm Building",
    subtitle: "Oral Surgery / Business / Creativity",
    metadata: ["CLE 10 Future Plan", "Jovan Pahal", "Personal Blueprint"],
    line: "A cinematic capstone about the future I can actually see myself building.",
    context: "This project connects healthcare, ownership, creativity, technology, and the freedom to keep improving my life.",
  },
  {
    number: "02",
    template: "text-reveal",
    title: "Who I Am",
    kicker: "Connected Interests",
    line: "I want a future where I don't have to give up one side of myself to build another.",
    context: "Healthcare, business, music, photography, and technology are not random interests. They are parts of one future system.",
    items: [
      "Healthcare / Science",
      "Business / Money",
      "Music Production",
      "Technology / Systems",
      "Photography / Visual Creativity",
      "Long-Term Goals / Freedom",
    ],
  },
  {
    number: "03",
    template: "archive",
    title: "This Started Early",
    kicker: "Personal Archive",
    typed: "Kindergarten: I wanted to be a dentist.",
    context: "The first idea was simple. The vision grew into oral surgery, ownership, technology, and a long-term plan.",
    lines: [
      "This started before this project.",
      "Kindergarten: I wanted to be a dentist.",
      "The idea stayed the same. The vision got bigger.",
    ],
    recordLabel: "Record",
    fileTitle: "Kindergarten Career Video",
    metadata: [
      "Topic: Future career",
      "Original clue: Kindergarten video",
      "Updated vision: Oral surgery + ownership",
    ],
  },
  {
    number: "04",
    template: "quote",
    title: "Big Question",
    kicker: "Core Question",
    quote: "How can I build a future that combines healthcare, business, creativity, and freedom?",
    context: "I do not want a career that only checks one box. I want the major parts of my life to support each other.",
    items: ["Healthcare", "Business", "Creativity", "Freedom"],
  },
  {
    number: "05",
    template: "dramatic-image",
    title: "Oral and Maxillofacial Surgery",
    kicker: "Career Direction",
    context: "This is the career focus because it combines science, precision, responsibility, advanced training, and business ownership.",
    lines: [
      "Oral and maxillofacial surgery is the career I can actually see myself building toward.",
      "It is serious, skilled, and still connects to business and ownership.",
    ],
    objectLabel: "Oral Surgery",
  },
  {
    number: "06",
    template: "system-object",
    title: "Why It Fits Me",
    kicker: "Fit System",
    center: "Oral Surgery",
    items: ["Skill", "Healthcare", "Business", "Lifestyle", "Freedom", "Helping People"],
    line: "It connects serious work with long-term options.",
    context: "For me, freedom means having choices, building things, and having more control over the life I work toward.",
  },
  {
    number: "07",
    template: "split",
    title: "Healthcare, But With Ownership",
    kicker: "Ownership Path",
    line: "I want a healthcare path where I can help people and still build something of my own.",
    context: "A dental practice is care, skill, a team, patient experience, systems, and a business all at the same time.",
    items: ["Care", "Skill", "Team", "Systems", "Ownership", "Growth"],
  },
  {
    number: "08",
    template: "pathway",
    title: "The Pathway",
    kicker: "Education Roadmap",
    roadmap: "High School Science -> University Prerequisites -> Dental School -> Licensing -> Specialty Training -> Oral Surgery -> Practice / Ownership / Expansion.",
    context: "The path is long, so I broke it into stages I can understand and work toward one step at a time.",
    stages: [
      "High School Science",
      "University Prerequisites",
      "Dental School",
      "Licensing",
      "Specialty Training",
      "Oral Surgery",
      "Practice / Ownership / Expansion",
    ],
    branches: [
      "General Dentistry",
      "Other Dental Specialties",
      "Business / Practice Ownership",
    ],
  },
  {
    number: "09",
    template: "file-stack",
    title: "Education and Training Options",
    kicker: "Research Stack",
    items: ["UBC", "University of Toronto", "University of Manitoba / OMFS Pathway", "Strategic First Year"],
    note: "UBC is my preferred path, but the smartest path is the one that helps me build the strongest grades, experience, and momentum.",
    context: "Toronto, Manitoba, and a strategic first year also matter because the best route is the one that builds real momentum.",
  },
  {
    number: "10",
    template: "sequence",
    title: "The Business Side of Dentistry",
    kicker: "Growth Sequence",
    line: "I don't just like the career. I like the idea of building and scaling the business behind it.",
    context: "A practice grows through people, systems, equipment, reputation, patient experience, and consistent decisions.",
    items: ["Team", "Systems", "Equipment", "Reputation", "Patient Experience", "Growth"],
    final: "One practice -> stronger systems -> more rooms -> better team -> another location -> future expansion.",
  },
  {
    number: "11",
    template: "practice-system",
    title: "What a Practice Actually Looks Like",
    kicker: "Practice Blueprint",
    line: "From the outside, a dental practice can look simple. Behind the scenes, it is a whole system.",
    context: "Understanding the system matters because ownership means knowing how care, scheduling, equipment, and people work together.",
    items: [
      "Front desk",
      "Scheduling",
      "Hygienists",
      "Assistants",
      "Patients",
      "Equipment",
      "X-rays",
      "Decisions",
      "Dentist moving between rooms",
    ],
  },
  {
    number: "12",
    template: "rotating",
    title: "Technology in Dentistry",
    kicker: "Digital Dentistry",
    context: "Dental scanning made the career feel modern and technical because a real mouth can become a digital model used for planning.",
    lines: [
      "A physical scan can become an STL digital model.",
      "That model can be rotated, studied, and used to plan treatment.",
      "Scanning my little brother's teeth made the technology feel real.",
    ],
    stlPaths: [
      "assets/dental/Visualization_DigitalModelUnsectioned_18-28.stl",
      "assets/dental/Visualization_DigitalModelUnsectioned_38-48.stl",
    ],
  },
  {
    number: "13",
    template: "network",
    title: "Practice Expansion",
    kicker: "Expansion Map",
    line: "A practice can grow into something bigger than one office.",
    context: "Expansion is not random. It depends on planning, investment, equipment, a strong team, and seeing opportunity clearly.",
    items: ["Planning", "Investment", "Equipment", "Growth", "Opportunity"],
    final: "A career can become a platform for building other things.",
  },
  {
    number: "14",
    template: "sequence",
    title: "Business Is a Skill Too",
    kicker: "Skill Transfer",
    line: "Even when a side project does not become huge, the skills still stay with you.",
    context: "Building, testing, organizing, and problem-solving are skills I can use later in school, websites, business, and ownership.",
    items: ["Build", "Test", "Learn", "Wrap Up", "Apply Later"],
    final: "The project might end, but the skill does not.",
  },
  {
    number: "15",
    template: "marquee",
    title: "Music Production",
    kicker: "Motion Loop",
    line: "Producing is creative, but it is also technical.",
    context: "Music production taught me that creative work still needs systems, taste, collaboration, and repeated practice.",
    items: ["Sound selection", "Arrangement", "Rhythm", "Mixing", "Collaboration", "Taste", "Practice"],
    final: "You need to be good at a lot of things to be a producer.",
  },
  {
    number: "16",
    template: "hover-image",
    title: "Waiting for the Right Moment",
    kicker: "Photography Lesson",
    quote: "You can always delete a bad picture, but you can't go back and take one you never tried to get.",
    context: "The same lesson applies to opportunities: notice the moment, try, and learn even if the first attempt is not perfect.",
    final: "That applies to more than photography.",
    asset: "assets/generated/photo-placeholder.svg?v=2",
  },
  {
    number: "17",
    template: "command",
    title: "Opportunity Is a Resource",
    kicker: "Working Notes",
    context: "Using tools well is not cheating the process. It helps me learn faster while I still make the decisions.",
    lines: [
      "AI does not replace my thinking.",
      "It helps me move faster with ideas, research, organization, and building.",
      "I still make the decisions.",
    ],
    final: "Doing everything alone is not automatically better.",
    items: ["Ideas", "Research", "Organization", "Building", "Testing", "Decisions"],
  },
  {
    number: "18",
    template: "quote",
    title: "Skill Opens Doors, People Show You Where They Are",
    kicker: "People And Skill",
    quote: "Skill matters, but people matter too. Connections do not replace skill - they create opportunities for skill.",
    context: "In dentistry, business, music, and learning, people can show where the doors are. Skill is what lets me walk through them.",
    items: ["Dentistry / Oral Surgery", "Business", "Music", "Learning from people ahead"],
  },
  {
    number: "19",
    template: "skill-wheel",
    title: "Skills I'm Building",
    kicker: "Skill System",
    center: "The Future I'm Building",
    context: "These skills are not only for one job. They support ownership, creativity, technology, planning, and adapting when plans change.",
    items: [
      "Business Thinking",
      "Creativity",
      "Technical Skill",
      "Long-Term Planning",
      "Adaptability",
      "Initiative",
    ],
  },
  {
    number: "20",
    template: "image-stack",
    title: "Making It Work Without Giving Things Up",
    kicker: "Connected Stack",
    line: "I do not want to give up one side of myself to build another.",
    context: "The goal is not doing everything randomly. It is making career, business, creativity, and experience support the same direction.",
    items: ["Oral Surgery", "Business", "Music", "Tech", "Photography", "Lifeguarding / Work", "School"],
    final: "The goal is to make everything support the future I'm building.",
  },
  {
    number: "21",
    template: "roadmap",
    title: "The Next Version of the Plan",
    kicker: "Final Build-Up",
    context: "Right now, the plan is school, science, grades, work experience, and projects. Later, it becomes dentistry, oral surgery, ownership, and still creating.",
    stages: ["Now", "Post-secondary", "Dental path", "Oral surgery", "Practice / business", "Keep creating"],
    items: [
      "Science / grades",
      "Meet or shadow oral surgeons",
      "Business / tech side projects",
      "Music sessions in university",
      "Photography / creative work",
      "Lifeguarding / work experience",
      "Earning money / responsibility",
      "Eventually building and scaling a practice",
    ],
  },
  {
    number: "22",
    template: "final",
    title: "Sources",
    kicker: "Sources / Credits",
    quote: "This is the direction I'm building toward, but I'm open to the plan getting better as I learn more.",
    context: "The project uses assignment requirements, dental education research, career research, and personal experience.",
    items: [
      "Assignment",
      "Canadian Dental Association",
      "Canadian Association of Oral and Maxillofacial Surgeons",
      "UBC Dentistry",
      "University of Toronto Dentistry",
      "University of Manitoba Dentistry",
      "Personal experience",
    ],
    final: "Website built by Jovan Pahal.",
  },
];
