export const storyBeats = [
  {
    key: "beat-1-opening",
    act: "PROJECTS",
    sectionId: "opening",
    phase: "default",
    desktopUnits: 2.2,
    mobileUnits: 1.8,
    autoplayMs: 2500,
    transitionIn: null,
    controller: "opening"
  },
  {
    key: "beat-2-opening-interlude",
    act: "PROJECTS",
    sectionId: "opening-interlude",
    phase: "default",
    desktopUnits: 1.6,
    mobileUnits: 1.4,
    autoplayMs: 2300,
    transitionIn: "opening",
    controller: "openingInterlude"
  },
  {
    key: "beat-3-project-log",
    act: "PROJECTS",
    sectionId: "project-log",
    phase: "default",
    desktopUnits: 3.5,
    mobileUnits: 3.1,
    autoplayMs: 4000,
    transitionIn: "element",
    controller: "projectLog"
  },
  {
    key: "beat-4-projects-interlude",
    act: "PROJECTS",
    sectionId: "projects-interlude",
    phase: "default",
    desktopUnits: 2.0,
    mobileUnits: 1.7,
    autoplayMs: 3000,
    transitionIn: "signal",
    controller: "projectsInterlude"
  },
  {
    key: "beat-5-music-introduction",
    act: "SOUND",
    sectionId: "music-introduction",
    phase: "default",
    desktopUnits: 2.0,
    mobileUnits: 1.7,
    autoplayMs: 2300,
    transitionIn: "signal",
    controller: "musicIntroduction"
  },
  {
    key: "beat-6-music-production",
    act: "SOUND",
    sectionId: "music-production",
    phase: "default",
    desktopUnits: 4.0,
    mobileUnits: 3.5,
    autoplayMs: 4300,
    transitionIn: "element",
    controller: "musicProduction"
  },
  {
    key: "beat-7-progress-interlude",
    act: "SOUND",
    sectionId: "music-progress",
    phase: "default",
    desktopUnits: 1.8,
    mobileUnits: 1.6,
    autoplayMs: 2200,
    transitionIn: "signal",
    controller: "musicProgress"
  },
  {
    key: "beat-8-music-opportunity",
    act: "SOUND",
    sectionId: "music-opportunity",
    phase: "default",
    desktopUnits: 3.4,
    mobileUnits: 3.0,
    autoplayMs: 4000,
    transitionIn: "element",
    controller: "musicOpportunity"
  },
  {
    key: "beat-9-photography-introduction",
    act: "PERSPECTIVE",
    sectionId: "photography-introduction",
    phase: "default",
    desktopUnits: 2.1,
    mobileUnits: 1.8,
    autoplayMs: 2300,
    transitionIn: "signal",
    controller: "photographyIntroduction"
  },
  {
    key: "beat-10-photography-sunglasses",
    act: "PERSPECTIVE",
    sectionId: "photography-sequence",
    phase: "sunglasses",
    desktopUnits: 2.5,
    mobileUnits: 2.2,
    autoplayMs: 3100,
    transitionIn: "element",
    controller: "photographySequence"
  },
  {
    key: "beat-11-photography-plane",
    act: "PERSPECTIVE",
    sectionId: "photography-sequence",
    phase: "plane",
    desktopUnits: 2.5,
    mobileUnits: 2.2,
    autoplayMs: 3200,
    transitionIn: "none",
    controller: "photographySequence"
  },
  {
    key: "beat-12-photography-temple-skytree",
    act: "PERSPECTIVE",
    sectionId: "photography-sequence",
    phase: "temple-skytree",
    desktopUnits: 2.5,
    mobileUnits: 2.2,
    autoplayMs: 3300,
    transitionIn: "none",
    controller: "photographySequence"
  },
  {
    key: "beat-13-photography-osaka-river",
    act: "PERSPECTIVE",
    sectionId: "photography-sequence",
    phase: "osaka-river",
    desktopUnits: 2.5,
    mobileUnits: 2.2,
    autoplayMs: 3200,
    transitionIn: "none",
    controller: "photographySequence"
  },
  {
    key: "beat-14-photography-cherry-blossoms",
    act: "PERSPECTIVE",
    sectionId: "photography-sequence",
    phase: "cherry-blossoms",
    desktopUnits: 2.5,
    mobileUnits: 2.2,
    autoplayMs: 3400,
    transitionIn: "none",
    controller: "photographySequence"
  },
  {
    key: "beat-15-photography-ending",
    act: "PERSPECTIVE",
    sectionId: "photography-ending",
    phase: "default",
    desktopUnits: 1.9,
    mobileUnits: 1.6,
    autoplayMs: 2200,
    transitionIn: "signal",
    controller: "photographyEnding"
  },
  {
    key: "beat-16-origin-interlude",
    act: "ORIGIN",
    sectionId: "origin-interlude",
    phase: "default",
    desktopUnits: 2.2,
    mobileUnits: 1.8,
    autoplayMs: 2900,
    transitionIn: "signal",
    controller: "originInterlude"
  },
  {
    key: "beat-17-kindergarten-archive",
    act: "ORIGIN",
    sectionId: "kindergarten-archive",
    phase: "default",
    desktopUnits: 3.6,
    mobileUnits: 3.2,
    autoplayMs: 4000,
    transitionIn: "element",
    controller: "kindergartenArchive"
  },
  {
    key: "beat-18-oral-surgery-reveal",
    act: "ORIGIN",
    sectionId: "oral-surgery-reveal",
    phase: "default",
    desktopUnits: 3.0,
    mobileUnits: 2.5,
    autoplayMs: 4200,
    transitionIn: "signal",
    controller: "oralSurgeryReveal"
  },
  {
    key: "beat-19-why-it-fits",
    act: "PRECISION",
    sectionId: "why-it-fits",
    phase: "default",
    desktopUnits: 3.2,
    mobileUnits: 2.8,
    autoplayMs: 4100,
    transitionIn: "element",
    controller: "whyItFits"
  },
  {
    key: "beat-20-dental-scan-introduction",
    act: "PRECISION",
    sectionId: "dental-scan-introduction",
    phase: "default",
    desktopUnits: 1.9,
    mobileUnits: 1.6,
    autoplayMs: 2300,
    transitionIn: "signal",
    controller: "dentalScanIntroduction"
  },
  {
    key: "beat-21-dental-model",
    act: "PRECISION",
    sectionId: "dental-model",
    phase: "default",
    desktopUnits: 4.2,
    mobileUnits: 3.7,
    autoplayMs: 4600,
    transitionIn: "element",
    controller: "dentalModel"
  },
  {
    key: "beat-22-healthcare-and-ownership",
    act: "PRECISION",
    sectionId: "healthcare-ownership",
    phase: "default",
    desktopUnits: 3.2,
    mobileUnits: 2.8,
    autoplayMs: 4100,
    transitionIn: "element",
    controller: "healthcareOwnership"
  },
  {
    key: "beat-23-practice-system",
    act: "BUILD",
    sectionId: "practice-system",
    phase: "default",
    desktopUnits: 3.3,
    mobileUnits: 2.9,
    autoplayMs: 4200,
    transitionIn: "signal",
    controller: "practiceSystem"
  },
  {
    key: "beat-24-building-project",
    act: "BUILD",
    sectionId: "building-project",
    phase: "project",
    desktopUnits: 4.0,
    mobileUnits: 3.5,
    autoplayMs: 4700,
    transitionIn: "element",
    controller: "buildingProject"
  },
  {
    key: "beat-25-practice-expansion",
    act: "BUILD",
    sectionId: "building-project",
    phase: "expansion",
    desktopUnits: 3.0,
    mobileUnits: 2.6,
    autoplayMs: 4400,
    transitionIn: "none",
    controller: "buildingProject"
  },
  {
    key: "beat-26-tools",
    act: "OPPORTUNITY",
    sectionId: "ai-tools",
    phase: "statement",
    desktopUnits: 2.0,
    mobileUnits: 1.7,
    autoplayMs: 2300,
    transitionIn: "signal",
    controller: "aiTools"
  },
  {
    key: "beat-27-how-i-use-ai",
    act: "OPPORTUNITY",
    sectionId: "ai-tools",
    phase: "process",
    desktopUnits: 3.3,
    mobileUnits: 2.9,
    autoplayMs: 4100,
    transitionIn: "none",
    controller: "aiTools"
  },
  {
    key: "beat-28-connections",
    act: "OPPORTUNITY",
    sectionId: "connections",
    phase: "default",
    desktopUnits: 3.4,
    mobileUnits: 3.0,
    autoplayMs: 4100,
    transitionIn: "element",
    controller: "connections"
  },
  {
    key: "beat-29-parts-continue",
    act: "OPPORTUNITY",
    sectionId: "continuation-stack",
    phase: "default",
    desktopUnits: 3.7,
    mobileUnits: 3.2,
    autoplayMs: 4300,
    transitionIn: "signal",
    controller: "continuationStack"
  },
  {
    key: "beat-30-integration",
    act: "OPPORTUNITY",
    sectionId: "integration",
    phase: "default",
    desktopUnits: 2.3,
    mobileUnits: 1.9,
    autoplayMs: 2300,
    transitionIn: "signal",
    controller: "integration"
  },
  {
    key: "beat-31-path",
    act: "DIRECTION",
    sectionId: "next-version",
    phase: "path",
    desktopUnits: 2.3,
    mobileUnits: 2.0,
    autoplayMs: 4600,
    transitionIn: "element",
    controller: "nextVersion"
  },
  {
    key: "beat-32-next-version",
    act: "DIRECTION",
    sectionId: "next-version",
    phase: "keep-going",
    desktopUnits: 4.0,
    mobileUnits: 3.5,
    autoplayMs: 5200,
    transitionIn: "none",
    controller: "nextVersion"
  },
  {
    key: "beat-33-sources",
    act: "DIRECTION",
    sectionId: "ending",
    phase: "sources",
    desktopUnits: 3.2,
    mobileUnits: 2.8,
    autoplayMs: 4800,
    transitionIn: "curtain",
    controller: "ending"
  },
  {
    key: "beat-34-ending",
    act: "DIRECTION",
    sectionId: "ending",
    phase: "final",
    desktopUnits: 3.0,
    mobileUnits: 2.6,
    autoplayMs: 4800,
    transitionIn: "none",
    controller: "ending"
  }
];

export const scrollUnitVh = 100;
